/**
 * Minimal Markdown model for our own deliverables (generated by tool pipelines — a known subset:
 * #/##/### headings, paragraphs, - bullets, 1. numbered lists, **bold**, _italic_). No HTML is ever
 * interpreted, so customer-visible output cannot inject markup. Sections split on "## " so the order
 * page can offer a copy button per section (MLS text, captions, hashtags…).
 */
export type Inline = { t: "text"; v: string } | { t: "bold"; v: string } | { t: "em"; v: string };
export type Block =
  | { kind: "heading"; level: 1 | 2 | 3; text: string }
  | { kind: "paragraph"; inlines: Inline[] }
  | { kind: "bullets"; items: Inline[][] }
  | { kind: "numbered"; items: Inline[][] };

export type Section = { title: string | null; blocks: Block[]; plain: string };

export function parseInline(s: string): Inline[] {
  const out: Inline[] = [];
  const re = /\*\*([^*]+)\*\*|_([^_]+)_/g;
  let last = 0;
  for (const m of s.matchAll(re)) {
    const i = m.index ?? 0;
    if (i > last) out.push({ t: "text", v: s.slice(last, i) });
    if (m[1] !== undefined) out.push({ t: "bold", v: m[1] });
    else out.push({ t: "em", v: m[2] });
    last = i + m[0].length;
  }
  if (last < s.length) out.push({ t: "text", v: s.slice(last) });
  return out;
}

export function parseMarkdown(md: string): Block[] {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const blocks: Block[] = [];
  let para: string[] = [];
  let list: { kind: "bullets" | "numbered"; items: string[] } | null = null;
  const flushPara = () => {
    if (para.length) blocks.push({ kind: "paragraph", inlines: parseInline(para.join(" ")) });
    para = [];
  };
  const flushList = () => {
    if (list) blocks.push({ kind: list.kind, items: list.items.map(parseInline) });
    list = null;
  };
  for (const raw of lines) {
    const line = raw.trimEnd();
    const h = /^(#{1,3})\s+(.*)$/.exec(line) ?? (/^\*\*([^*]+)\*\*$/.test(line) ? ["", "###", line.slice(2, -2)] : null); // a lone **label** line is a sub-heading
    const b = /^[-*]\s+(.*)$/.exec(line);
    const n = /^\d+[.)]\s+(.*)$/.exec(line);
    if (h) {
      flushPara();
      flushList();
      blocks.push({ kind: "heading", level: h[1].length as 1 | 2 | 3, text: h[2].trim() });
    } else if (b) {
      flushPara();
      if (!list || list.kind !== "bullets") {
        flushList();
        list = { kind: "bullets", items: [] };
      }
      list.items.push(b[1]);
    } else if (n) {
      flushPara();
      if (!list || list.kind !== "numbered") {
        flushList();
        list = { kind: "numbered", items: [] };
      }
      list.items.push(n[1]);
    } else if (line.trim() === "") {
      flushPara();
      flushList();
    } else {
      flushList();
      para.push(line.trim());
    }
  }
  flushPara();
  flushList();
  return blocks;
}

function plainOf(blocks: Block[]): string {
  const inl = (xs: Inline[]) => xs.map((x) => x.v).join("");
  return blocks
    .map((b) => {
      if (b.kind === "heading") return b.text;
      if (b.kind === "paragraph") return inl(b.inlines);
      if (b.kind === "bullets") return b.items.map((i) => `• ${inl(i)}`).join("\n");
      return b.items.map((i, idx) => `${idx + 1}. ${inl(i)}`).join("\n");
    })
    .join("\n\n");
}

/** Split into copyable sections at level-2 headings; the section's plain text excludes its heading. */
export function markdownSections(md: string): Section[] {
  const blocks = parseMarkdown(md);
  const sections: Section[] = [];
  let current: { title: string | null; blocks: Block[] } = { title: null, blocks: [] };
  for (const b of blocks) {
    if (b.kind === "heading" && b.level === 2) {
      if (current.blocks.length || current.title) sections.push({ ...current, plain: plainOf(current.blocks) });
      current = { title: b.text, blocks: [] };
    } else if (b.kind === "heading" && b.level === 1 && !current.title && current.blocks.length === 0) {
      // document title: keep it as the first section's heading, not as copy material
      current.blocks.push(b);
    } else {
      current.blocks.push(b);
    }
  }
  if (current.blocks.length || current.title) sections.push({ ...current, plain: plainOf(current.blocks) });
  return sections;
}
